### ISSUE TITLE
error with mblite.py --init

### ISSUE THREAD

**Issue by donaldsteele** [sampsyo/mblite#1]
when executing /mblite.py --init

i am getting the error below
```

user@s1:~/scripts/mblite# ./mblite.py --init
Traceback (most recent call last):
  File "./mblite.py", line 200, in <module>
    script = ''.join(convert_createtables(open(tables_sql)))
  File "./mblite.py", line 83, in convert_createtables
    raise ValueError('unknown kind in %s' % repr(line))
ValueError: unknown kind in 'data JSONB NOT NULL,'
```

**Comment by sampsyo** [comment]
Hi! It's clearly been a while since I've worked on this—seems like some things changed in the MB schema. In any case, I tried adding a handler for this type—maybe give the above commit a try?

**Comment by donaldsteele** [comment]
This did the trick thanks!
